quarkus.datasource.db-kind=
quarkus.datasource.username=
quarkus.datasource.password=
quarkus.datasource.jdbc.url=

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=authorization,content-type,origin
